# -*- coding: utf-8 -*-
"""text_completion_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5fOaG2lCHWjKKuUJDa7Z1ZYLfBqciJJ

# Capstone Project: AI-Powered Text Completion
## Author: Serenity Smith
"""

!pip install cohere

from cohere import ClientV2
API_KEY = ""

client = ClientV2(api_key=API_KEY)
client.chat_stream(
	model="command-a-03-2025",
	messages=[],
	temperature=0.8
)

print("Welcome to the Text Completion App with Cohere!")
print("Type 'exit' to end the session.\n")

while True:
  user_input = input("Enter your prompt: \n").strip()
  if user_input.lower() == "exit":
    print("See you again soon!\n")
    break
  if not user_input:
    print("Please try again and enter a non-empty prompt.\n")
    continue
  try:
    response = client.generate(
        model="command",
        prompt=user_input,
        max_tokens=500,
        temperature=0.8
    )
    print("\nAI Response:")
    print(response.generations[0].text, "\n")
  except Exception as e:
    print("Something went wrong:", e)
  finally:
    print("Powered by Cohere AI\n")